spring:
  application:
    name: clam-order-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/clamdb
    driver-class-name: org.postgresql.Driver
    username: clamuser
    password: clampassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
# Server
server:
  port: 8080

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.project.clamorderbackend: DEBUG
    org.springframework.web: INFO
